name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

jobs:
- job: windows2022pwsh
  displayName: Windows 2022 PowerShell 7
  pool:
    vmImage: windows-2022
  steps:
  - template: templates/ci-general.yml

- job: macOS11
  displayName: macOS 11
  pool:
    vmImage: macOS-11
  steps:
  - template: templates/ci-general.yml

- job: ubuntu2004
  displayName: Ubuntu 20.04
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: templates/ci-general.yml
