# escape=`
#0.3.6 (no powershell 6)
FROM microsoft/dotnet-framework:4.7.1
LABEL maintainer='PowerShell Team <powershellteam@hotmail.com>'
LABEL description="Build's GraphicalTools"

SHELL ["C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-command"]

COPY dockerInstall.psm1 containerFiles/dockerInstall.psm1

RUN Import-Module PackageManagement; `
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; `
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted | Out-Null; `
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1 -outfile C:/dotnet-install.ps1; `
    C:/dotnet-install.ps1 -Channel Release -Version 2.1.4; `
    Add-Path C:/Users/ContainerAdministrator/AppData/Local/Microsoft/dotnet; `
    Install-Module InvokeBuild -Scope CurrentUser -Force; `
    Install-Module platyPS -Scope CurrentUser -Force;

RUN Install-Module -Name PowerShellGet -Force;

# Copy build script over
COPY build.ps1 containerFiles/build.ps1

# Uncomment to debug locally
# RUN Import-Module ./containerFiles/dockerInstall.psm1; `
#     Install-ChocolateyPackage -PackageName git -Executable git.exe; `
#     git clone https://github.com/PowerShell/PowerShellEditorServices;

ENTRYPOINT ["C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-command"]
